# Generated by Django 2.2.6 on 2019-11-02 10:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('avatar', models.ImageField(blank=True, default='question/static/avatars/avatar.png', upload_to='question/static/avatars/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('head', models.CharField(max_length=200, verbose_name='')),
                ('body', models.TextField(verbose_name='Body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Member', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=40, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='TagPivot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'TagPivot',
                'verbose_name_plural': 'TagPivots',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Member', verbose_name='Author')),
                ('que', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
