# Generated by Django 2.2.6 on 2019-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20191102_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(to='question.Question'),
        ),
        migrations.DeleteModel(
            name='TagPivot',
        ),
    ]
